import { useRouter } from "next/router";
import type { NextPage } from 'next';
import Head from 'next/head';
//import Image from 'next/image';
import { useContext, useEffect, useState } from 'react';
import styles from '../../styles/Room.module.css';
import { SocketContext } from '../../context/SocketContext';
import PlayerComponent from '../../components/player/PlayerComponent';
import getYoutubeVideoId from "../../utils/getYoutubeVideoId";
import ChatMessage from "../../components/ChatMessage";
import { AuthContext } from "../../context/AuthContext";
import Loading from "../../components/screens/Loading";

const formatMessage = (str: string) => {
  const formattedString = str.replace(/\s{2,}/g, ' ').trim();
  if (formattedString === null || formattedString.match(/^ *$/) !== null) return false;
  return formattedString;
}

const Room: NextPage = () => {
  const router = useRouter();
  const {code} = router.query;
  const {socket, changeRoom, currentSongPlaylist} = useContext(SocketContext);
  const {authState} = useContext(AuthContext);
  const [socketConnected, setSocketConnected] = useState(false);
  const [messages, setMessages] = useState([] as any);
  const [message, setMessage] = useState('');
  const [url, setUrl] = useState('');
  const [roomPassword, setRoomPassword] = useState('');
  const [connectedToRoom, setConnectedToRoom] = useState(false);
  const [codeAvailable, setCodeAvailable] = useState(false);

  useEffect(() => {
    if (authState === false) router.replace('/login');
  }, [authState]);

  // checks to see if socket successfully connected to server
  useEffect(() => {
    setSocketConnected(socket.connected);
    
    socket.on('connect', () => {
      setSocketConnected(socket.connected);
    });

    socket.on('join-status', (data: boolean) => {
      setConnectedToRoom(data);
    });

    socket.on('disconnect', () => {
      setSocketConnected(() => (socket.connected));
    });
  }, [socket?.connected]);

  useEffect(() => {
    if (!code) return;

    setCodeAvailable(true);
    //handleRoomConnection();
  }, [code]);

  useEffect(() => {
    if (!socketConnected || !codeAvailable) return;

    handleRoomConnection();
  }, [socketConnected, codeAvailable]);

  // now this is fun
  // checks if room code is the correct length, then just emits join to the back-end to that room
  const handleRoomConnection = () => {
    const correctedRoomCode = `${code}`.split(" ").join("").trim();
    //console.log(correctedRoomCode.length >= 5, room.length);
    if (correctedRoomCode.length >= 5 && !/[^a-zA-Z]/.test(correctedRoomCode)) {
      if (!code) return;

      socket.emit('join', {room: correctedRoomCode, password: roomPassword});
    } else {
      alert('Room code is less than the accepted!');
    }
  }

  const handleSongRequest = () => {
    if (socketConnected) {
      socket.emit('request-song', url);
    }
  }

  const handleSendMessage = () => {
    const formattedMessage = formatMessage(message);
    if (formattedMessage == false) return;
    socket.emit('send-message', {message: formattedMessage, room: code});
    setMessage('');
  }

  useEffect(() => {
    if (!connectedToRoom) return;

    socket.on('message', (data: any) => {
      setMessages((messages: any) => [...messages, data]);
    });
    
    changeRoom(code as string);
  }, [connectedToRoom]);

  if (authState === undefined || authState === false) {
    return <Loading />;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>{!code ? 'TuneTogether' : `TuneTogether - Room - ${code}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div className={styles.sidebar}>
        <button className={styles.sidebarButtonTop}>
          <HomeIcon />
        </button>

        <div className={styles.buttonsHandler}>
          <NavbarButton buttonName={"Add Music"}>
            <PlusIcon />
          </NavbarButton>
          <NavbarButton buttonName={"Search Rooms"}>
            <SearchIcon />
          </NavbarButton>
          <NavbarButton buttonName={"Enter room code"}>
            <SignInIcon />
          </NavbarButton>
          <NavbarButton buttonName={"Create new room"}>
            <PlusCircleIcon />
          </NavbarButton>
        </div>

        <button className={styles.sidebarButtonBottom}>
          <PersonIcon />
        </button>
      </div> */}

      {/* <div className={styles.main}>
        hi
      </div> */}

      {/* <div className={styles.chatRoom}>
        <div className={styles.MessagesHandler}>
          {messages.length > 0 ? messages.map((msg: any, i: number) => (
            <ChatMessage key={i} user={msg.user as string}>
              {msg.text}
            </ChatMessage>
          )).reverse() : ('Nada Além de Galinhas!')}
        </div>
        <div className={styles.chatMessengerHandler}>
          <textarea onChange={(e) => setMessage(e.target.value)} value={message} onKeyDown={(event) => {if (event.key === 'Enter') {handleSendMessage(); event.preventDefault()}}} rows={3} name="" id="" />
          <button disabled={formatMessage(message) == false ? true : false} onClick={handleSendMessage}>Send</button>
        </div>
      </div> */}

      {/* <nav className={styles.topBar}>
        <ul>
          <li className={styles.logo}>
            TuneTogether  
          </li>  

          <li>
            Rooms
          </li>
          
          <li>
            Playlists
          </li>
        </ul>
      </nav> */}

      <div className={styles.main}>
        <div className={styles.mainSidebar}>
          <h1>TuneTogether</h1>

          <nav className={styles.topBar}>
            <ul>
              <li className={styles.logo}>
                TuneTogether  
              </li>  

              <li>
                Rooms
              </li>
              
              <li>
                Playlists
              </li>
            </ul>
          </nav>
        </div>
        <div className={styles.playerContainer}>

          <div className={styles.centralizePlayerVertically}>
            <PlayerComponent />
          </div>
          
          
          <h1>Next to play</h1>

          <div className={styles.roomPlaylist}>
            {currentSongPlaylist.map((item) => (
              <div className={styles.playlistItem}>
                <div className={styles.cover} style={{
                  background: `url(https://img.youtube.com/vi/${getYoutubeVideoId(item.song_url) || item.song_url}/maxresdefault.jpg)`
                }}>
                </div>
                <div className={styles.songName}>
                  <h1>{item.title}</h1>
                  <span>From {item.channelTitle}</span>
                </div>
                <div className={styles.requestedByInPlaylist}>
                  <h1>Requested by:</h1>
                  <span>{item.requested_by}</span>
                </div>
              </div>
            ))}
          </div>

          {currentSongPlaylist.length === 0 && <h1>¯\_(ツ)_/¯ nothing here... yet</h1>}
        </div>
        <div className={styles.chat}>
          <div className={styles.chatContainer}>
            <h1>Chat</h1>

            <div className={styles.messagesContainer}>
              {messages.length > 0 ? messages.map((msg: { user: string, text: string }, i: number) => (
                <ChatMessage key={i} user={msg.user as string} style={{
                  background: (i+1)%2 === 0 ? 'rgba(0,0,0,.2)' : 'none'
                }}>
                  {msg.text}
                </ChatMessage>
              )).reverse() : ('Nada Além de Galinhas!')} 
              {/* temporary */}
            </div>

            <div className={styles.chatMessengerHandler}>
              <textarea placeholder="Write your message here!" className={styles.messageInput} onChange={(e) => setMessage(e.target.value)} value={message} onKeyDown={(event) => {if (event.key === 'Enter') {handleSendMessage(); event.preventDefault()}}} rows={2} name="" id="" />
              <div className={styles.chatButtons}>
                <button className={styles.chatSettingsButton}>
                  <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512">
                    {/* <!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --> */}
                    <path d="M495.9 166.6c3.2 8.7 .5 18.4-6.4 24.6l-43.3 39.4c1.1 8.3 1.7 16.8 1.7 25.4s-.6 17.1-1.7 25.4l43.3 39.4c6.9 6.2 9.6 15.9 6.4 24.6c-4.4 11.9-9.7 23.3-15.8 34.3l-4.7 8.1c-6.6 11-14 21.4-22.1 31.2c-5.9 7.2-15.7 9.6-24.5 6.8l-55.7-17.7c-13.4 10.3-28.2 18.9-44 25.4l-12.5 57.1c-2 9.1-9 16.3-18.2 17.8c-13.8 2.3-28 3.5-42.5 3.5s-28.7-1.2-42.5-3.5c-9.2-1.5-16.2-8.7-18.2-17.8l-12.5-57.1c-15.8-6.5-30.6-15.1-44-25.4L83.1 425.9c-8.8 2.8-18.6 .3-24.5-6.8c-8.1-9.8-15.5-20.2-22.1-31.2l-4.7-8.1c-6.1-11-11.4-22.4-15.8-34.3c-3.2-8.7-.5-18.4 6.4-24.6l43.3-39.4C64.6 273.1 64 264.6 64 256s.6-17.1 1.7-25.4L22.4 191.2c-6.9-6.2-9.6-15.9-6.4-24.6c4.4-11.9 9.7-23.3 15.8-34.3l4.7-8.1c6.6-11 14-21.4 22.1-31.2c5.9-7.2 15.7-9.6 24.5-6.8l55.7 17.7c13.4-10.3 28.2-18.9 44-25.4l12.5-57.1c2-9.1 9-16.3 18.2-17.8C227.3 1.2 241.5 0 256 0s28.7 1.2 42.5 3.5c9.2 1.5 16.2 8.7 18.2 17.8l12.5 57.1c15.8 6.5 30.6 15.1 44 25.4l55.7-17.7c8.8-2.8 18.6-.3 24.5 6.8c8.1 9.8 15.5 20.2 22.1 31.2l4.7 8.1c6.1 11 11.4 22.4 15.8 34.3zM256 336a80 80 0 1 0 0-160 80 80 0 1 0 0 160z"/>
                  </svg>
                </button>
                <button className={styles.submitMessageButton} disabled={formatMessage(message) == false ? true : false} onClick={handleSendMessage}>Send</button>
              </div>
            </div>
            
          </div>

          {/* <div className={styles.userList}>
            <h1>Online Users</h1>

            <div className={styles.usersContainer}>
              <div>
                <img src="https://media.discordapp.net/attachments/1124003308248510535/1124491830361325619/Turtle.jpg?width=247&height=247" alt="" />

                <span>Teste</span>
              </div>
            </div>
          </div> */}

          {/* <div className={styles.options}>
            <button>dps mudar</button>
          </div> */}
        </div>
      </div>

      <div className={styles.socketIODebugMenu}>
          {socket.connected && 'connected'}
          {socket.disconnected && 'disconnected'}

        <input type="text" onChange={ (e) => setUrl(e.target.value) } />
        <input type="button" value={`request song`} onClick={handleSongRequest} />
      </div>
    </div>
  )
}

export default Room;