import axios from 'axios';
import e from 'express';
import type { NextPage } from 'next';
import Head from 'next/head';
import React, { useState } from 'react';
import styles from '../styles/Home.module.css';

const Login: NextPage = () => {
  const [email, setEmail] = useState('' as any);
  const [password, setPassword] = useState('' as any);

  const handleAuthentication = (e: React.FormEvent) => {
    e.preventDefault();

    axios.post('http://localhost:3000/api/auth', {email, password});
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Main - sockets tests</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      e-mail: <input type="text" onChange={ (e) => setEmail(e.target.value) } />
      password: <input type="password" onChange={ (e) => setPassword(e.target.value) } />

      <input type="button" value={`login`} onClick={handleAuthentication} />
    </div>
  )
}

export default Login;
